name: framework_builder
description: Generate Framework Routes.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  analyzer: ^4.1.0
  build: ^2.2.1

  framework_annotations:
    path: ../framework_annotations

  meta: ^1.7.0
  source_gen: ^1.2.1
  code_builder: ^4.0.0
  dart_style: ^2.0.0

dev_dependencies:
  generator_test: ^0.1.0
  json_annotation: ^4.4.0
  test: ^1.16.0
  very_good_analysis: ^2.4.0
  app:
    path: ../framework

scripts: ../../derry.yaml

import_sorter:
  comments: false