name: framework_annotations
description: The annotation package for the framework generator.
version: 0.1.0
homepage:

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  meta: ^1.7.0

dev_dependencies:
  test: ^1.16.0
  very_good_analysis: ^2.4.0

import_sorter:
  comments: false