name: app
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  event_bus: ^2.0.0
  rxdart: ^0.27.5
  uuid: ^3.0.6
  logger: ^1.1.0
  collection: ^1.16.0
  synchronized: ^3.0.0+2
  solid_bottom_sheet: ^0.1.10
  get_it: ^7.2.0

  bvvm: ^0.0.1+1
  observable_value: ^0.0.1+2
  abstract_kv_store: ^0.0.1+2
  element_tree_child_locator: ^0.0.1+1
  lenient_equality: ^0.0.1
  v_widgets: ^0.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
